apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-storage-class
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
